/**
 * Release-gate runner — executes `.agent-state/RELEASE_GATES.md` instead of
 * trusting it, and refuses to certify a stale source of truth.
 *
 * Three things this replaces, and why:
 *
 *  1. The Command column is a DOCUMENT, not an authority. It reads `npm test`,
 *     `npm run build`, … while AGENTS.md declares bun canonical. This runner
 *     never shells out to npm/npx/pnpm/yarn: it maps each command to its bun
 *     equivalent, executes THAT, records the mapping, rewrites the column, and
 *     hard-aborts if a forbidden package manager ever reaches an argv[0].
 *
 *  2. The Status column was hand-maintained and drifted 48 artworks away from
 *     the catalog: it claimed "139 published" / "169 approved → 139 projected"
 *     against a catalog that computes 217 approved / 187 publishable. A
 *     freshness-by-date check cannot see that; a numeric cross-check can. Every
 *     `<N> published|approved|projected` claim in `.agent-state/*.md` is
 *     compared against `scripts/agent/rights-audit.mjs` (P10 — the single
 *     computation of catalog truth; this runner parses its JSON and never
 *     recomputes the numbers itself). A mismatch is SOURCE-OF-TRUTH-CONFLICT.
 *     Stated default resolution: the computed value wins.
 *
 *  3. PASS was assertable by typing it. Here PASS is derivable only from a
 *     captured child exit code that was written to the run log first. Anything
 *     that needs credentials, a live service, a browser, or an absent CLI is
 *     written NOT RUN with the reason. There is no third way to reach PASS.
 *
 * SCOPE OF AUTOMATIC REWRITE (deliberately narrow, stated honestly):
 *   - The Status column of the RELEASE_GATES table is machine-generated from
 *     this run. Prior hand-written detail is NOT preserved — that detail is
 *     precisely what went stale. Fresh detail is the tail of the child's own
 *     output plus, for catalog gates, the computed counts.
 *   - Numeric claims OUTSIDE that table (other `.agent-state/*.md` files, the
 *     launch-blocker prose) are REPORTED, never silently rewritten.
 *     `DECISIONS.md` in particular is an append-only ledger whose superseded
 *     numbers are correct *as history*; rewriting them would destroy the audit
 *     trail the ADR exists to provide.
 *
 * Modes:
 *   (default)   execute every mapped gate, rewrite the table, append an ADR
 *               when a conflict was corrected
 *   --dry-run   run the cross-check and print the command plan; execute
 *               nothing, write nothing
 *   --today=YYYY-MM-DD   override the Status date (default: system date)
 *
 * FAIL-MODE: closed. An unresolvable bun, an unparseable table, an unreadable
 * catalog, or a forbidden spawn aborts without writing a status. Exit codes:
 *   0 every executed gate passed
 *   1 an executed gate failed
 *   2 the runner could not establish ground truth (nothing was certified)
 *
 * Run log: C:\Users\serge\.claude\logs\release-gates.jsonl (append-only JSONL,
 * on C:, outside both repos, so it is never part of any working tree).
 */
import { spawnSync } from "node:child_process";
import { appendFileSync, existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..", "..");
const STATE_DIR = path.join(ROOT, ".agent-state");
const GATES_FILE = path.join(STATE_DIR, "RELEASE_GATES.md");
const DECISIONS_FILE = path.join(STATE_DIR, "DECISIONS.md");
const AUDITOR = path.join(ROOT, "scripts", "agent", "rights-audit.mjs");
const LOG_DIR = path.join(homedir(), ".claude", "logs");
const LOG = path.join(LOG_DIR, "release-gates.jsonl");

const DRY_RUN = process.argv.includes("--dry-run");
const TODAY = (process.argv.find((a) => a.startsWith("--today="))?.slice("--today=".length)) ||
  new Date().toISOString().slice(0, 10);
const RUN_ID = `${TODAY}T${new Date().toISOString().slice(11, 19)}Z`;

const BEGIN_MARK = "<!-- release-gates:begin (generated by scripts/agent/release-gates.mjs — do not hand-edit) -->";
const END_MARK = "<!-- release-gates:end -->";

/** Package managers this runner must never spawn. AGENTS.md: bun is canonical. */
const FORBIDDEN_RUNNERS = /^(npm|npx|pnpm|yarn)(\.cmd|\.exe)?$/i;

function abort(reason) {
  console.error(`\n[release-gates] ABORT: ${reason}`);
  console.error("[release-gates] Nothing was certified and no file was rewritten.");
  process.exit(2);
}

function log(row) {
  const full = { v: 1, ts: new Date().toISOString(), actor: "release-gates", run: RUN_ID, ...row };
  if (DRY_RUN) return full;
  try {
    mkdirSync(LOG_DIR, { recursive: true });
    appendFileSync(LOG, JSON.stringify(full) + "\n");
  } catch (cause) {
    // A logging failure must not manufacture a PASS: PASS is derived from the
    // in-memory record only after this call returns, and certifyStatus below
    // refuses any row that is not marked logged.
    full.logged = false;
    full.logError = cause.code ?? cause.message;
    return full;
  }
  full.logged = true;
  return full;
}

/* ------------------------------------------------------------------ *
 * 1. Ground truth: P10's auditor. Parsed, never reimplemented.
 * ------------------------------------------------------------------ */

function computeCatalogTruth() {
  if (!existsSync(AUDITOR)) abort(`rights auditor absent at ${AUDITOR} — cannot establish catalog truth.`);
  const child = spawnSync(process.execPath, [AUDITOR], { cwd: ROOT, encoding: "utf8", shell: false });
  if (child.error) abort(`rights-audit spawn failed: ${child.error.code ?? child.error.message}`);
  if (child.status !== 0) abort(`rights-audit exited ${child.status} — refusing to cross-check against an untrusted count.\n${child.stderr ?? ""}`);
  let report;
  try {
    report = JSON.parse(child.stdout);
  } catch (cause) {
    abort(`rights-audit output is not JSON (${cause.message}) — refusing to guess catalog counts.`);
  }
  for (const key of ["total", "approved", "publishable"]) {
    if (typeof report[key] !== "number") abort(`rights-audit report is missing numeric "${key}" — schema drift; refusing to cross-check.`);
  }
  return report;
}

/* ------------------------------------------------------------------ *
 * 2. Table parsing
 * ------------------------------------------------------------------ */

function splitCells(line) {
  return line.replace(/^\s*\|/, "").replace(/\|\s*$/, "").split("|").map((c) => c.trim());
}

function parseGatesDoc(text) {
  const lines = text.split(/\r?\n/);
  const start = lines.findIndex((l) => /^\s*\|\s*Gate\s*\|/i.test(l));
  if (start < 0) abort(`${GATES_FILE} has no "| Gate |" table header — its structure changed; refusing to guess.`);
  if (!/^\s*\|[\s:|-]+\|\s*$/.test(lines[start + 1] ?? "")) abort(`${GATES_FILE} table header is not followed by a separator row — refusing to guess.`);
  let end = start + 2;
  while (end < lines.length && /^\s*\|/.test(lines[end])) end += 1;

  const rows = [];
  for (let i = start + 2; i < end; i += 1) {
    const cells = splitCells(lines[i]);
    if (cells.length < 4) abort(`${GATES_FILE} line ${i + 1} has ${cells.length} cells, expected 4 — refusing to guess.`);
    const [gate, requirement, command, status] = cells;
    const id = /\*\*(G\d+)\s*:/.exec(gate)?.[1] ?? /^(G\d+)\b/.exec(strip(gate))?.[1] ?? null;
    if (!id) abort(`${GATES_FILE} line ${i + 1} has no recognisable gate id in "${gate}" — refusing to guess.`);
    rows.push({ id, gate, requirement, command, status, sourceLine: i + 1 });
  }
  if (rows.length === 0) abort(`${GATES_FILE} table has no data rows.`);
  return { lines, headerIndex: start, tableEnd: end, rows };
}

function strip(s) {
  return s.replace(/[*`]/g, "");
}

/** Repo-relative, forward-slashed — the same path shape the docs already use. */
function rel(file) {
  return path.relative(ROOT, file).split(path.sep).join("/");
}

function cellSafe(s) {
  return String(s)
    .split(homedir())
    .join("~")
    .split(ROOT)
    .join(".")
    .replace(/\r?\n/g, " ")
    .replace(/\|/g, "\\|")
    .replace(/\s+/g, " ")
    .trim();
}

/* ------------------------------------------------------------------ *
 * 3. Command mapping — npm is never spawned
 * ------------------------------------------------------------------ */

function resolveBun() {
  const cherry = "C:\\Users\\serge\\.cherrystudio\\bin\\bun.exe";
  if (existsSync(cherry)) return cherry;
  const probe = spawnSync("bun", ["--version"], { shell: false, encoding: "utf8" });
  if (probe.status === 0) return "bun";
  return null;
}

/**
 * Map one backticked token from the Command column.
 * Returns an executable plan, or a non-executable reference with the reason
 * it is not runnable. A token is executable only if it names a known package
 * runner or an existing test file; anything else is a documentation reference.
 */
function mapCommand(raw, bun) {
  const text = raw.trim();
  const tokens = text.split(/\s+/);
  const head = tokens[0];

  if (head === "npm" || head === "pnpm" || head === "yarn") {
    const rest = tokens[1] === "run" ? tokens.slice(2) : tokens.slice(1);
    if (rest.length === 0) return { kind: "reference", text, why: `"${text}" names no script` };
    return {
      kind: "exec",
      binary: bun,
      args: ["run", ...rest],
      display: `bun run ${rest.join(" ")}`,
      mappedFrom: text,
      mapping: `${text} → bun run ${rest.join(" ")}`,
    };
  }

  // Already-canonical forms — including the ones a previous run wrote back into
  // the column. Re-parsing this file must be idempotent, or the runner demotes
  // its own output to NOT RUN on the next run.
  if (head === "bun") {
    return { kind: "exec", binary: bun, args: tokens.slice(1), display: text, mappedFrom: null, mapping: null };
  }
  if (head === "node") {
    return { kind: "exec", binary: process.execPath, args: tokens.slice(1), display: text, mappedFrom: null, mapping: null };
  }

  if (/^tests\/.+\.test\.tsx?$/.test(text) && existsSync(path.join(ROOT, text))) {
    const args = ["--test", "--experimental-strip-types", text];
    return {
      kind: "exec",
      binary: process.execPath,
      args,
      display: `node ${args.join(" ")}`,
      mappedFrom: text,
      mapping: `${text} (a test file, not a command) → node --test --experimental-strip-types ${text}`,
    };
  }

  return { kind: "reference", text, why: `"${text}" is a file/artifact reference, not a runnable command` };
}

function extractTokens(commandCell) {
  const found = [...commandCell.matchAll(/`([^`]+)`/g)].map((m) => m[1]);
  return found;
}

/* ------------------------------------------------------------------ *
 * 4. Preconditions — the only route to NOT RUN
 * ------------------------------------------------------------------ */

function probeCli(bin) {
  const child = spawnSync(bin, ["--version"], { shell: false, encoding: "utf8" });
  if (child.error) return { present: false, why: `spawn ${child.error.code ?? child.error.message}` };
  if (child.status !== 0) return { present: false, why: `exit ${child.status}` };
  return { present: true, version: (child.stdout ?? "").trim().split(/\r?\n/)[0] };
}

const PRECONDITIONS = {
  G5: () =>
    process.env.ARTCOVR_GATES_E2E === "1"
      ? null
      : "requires live services this runner does not start — playwright.config.ts spawns a Next dev server on 127.0.0.1:45180 and drives an installed Chrome channel. Opt in explicitly with ARTCOVR_GATES_E2E=1.",
  // G8 is `bun run db:verify`, which applies every migration to a DISPOSABLE
  // database and runs the contract + behavioural suites. It needs psql and a
  // reachable PostgreSQL — not the Supabase CLI, and not production
  // credentials. Requiring those was why this gate could never run.
  G8: () => {
    const cli = probeCli("psql");
    if (!cli.present) {
      return `requires a PostgreSQL client: the \`psql\` binary is not installed (${cli.why}). Install postgresql-client, point PGHOST/PGPORT/PGUSER at a disposable instance, and re-run.`;
    }
    const probe = spawnSync("psql", ["-tAc", "select 1"], {
      encoding: "utf8",
      timeout: 15_000,
      env: { ...process.env, PGDATABASE: process.env.PGDATABASE ?? "postgres", PGCONNECT_TIMEOUT: "10" },
    });
    if (probe.status !== 0) {
      const why = (probe.stderr ?? "").trim().split(/\r?\n/)[0] || `exit ${probe.status}`;
      return `requires a reachable disposable PostgreSQL: psql could not connect (${why}). Set PGHOST/PGPORT/PGUSER and re-run. NEVER point this at production — it creates a database and writes rows.`;
    }
    return null;
  },
};

/* ------------------------------------------------------------------ *
 * 5. Numeric cross-check
 * ------------------------------------------------------------------ */

const CLAIM_KINDS = [
  { kind: "published", re: /(\d+)\s+published\b/gi },
  { kind: "approved", re: /(\d+)\s+approved\b/gi },
  { kind: "projected", re: /(\d+)\s+projected\b/gi },
];

function truthFor(kind, truth) {
  // published/projected both mean "rows that reach the public projection" =
  // approved rows minus delete-tier = the auditor's `publishable`.
  if (kind === "approved") return { value: truth.approved, basis: "rights-audit.approved (rows passing rights/published/price)" };
  return { value: truth.publishable, basis: "rights-audit.publishable (approved rows minus delete-tier)" };
}

function scanClaims(fileText, filePath) {
  const claims = [];
  fileText.split(/\r?\n/).forEach((line, idx) => {
    const flat = strip(line);
    for (const { kind, re } of CLAIM_KINDS) {
      re.lastIndex = 0;
      let m;
      while ((m = re.exec(flat)) !== null) {
        claims.push({ file: filePath, line: idx + 1, kind, stated: Number(m[1]), context: flat.trim().slice(0, 160) });
      }
    }
  });
  return claims;
}

/**
 * Three scopes, because "stale" and "historical" are not the same thing:
 *   table   — the RELEASE_GATES Status column. This runner owns it and
 *             regenerates it, so a mismatch here is corrected in place.
 *   prose   — any other present-tense `.agent-state/*.md` line. A mismatch is
 *             a real SOURCE-OF-TRUTH-CONFLICT, but the runner only reports it:
 *             it cannot verify the surrounding sentence's arithmetic.
 *   ledger  — DECISIONS.md. An append-only record of dated decisions: its
 *             numbers are history by construction, so a mismatch there is a
 *             HISTORICAL-CLAIM, not a conflict, and editing it would destroy
 *             the audit trail. Reported for visibility, never acted on.
 */
function crossCheck(truth, parsed) {
  const conflicts = [];
  const agreements = [];
  const historical = [];

  const record = (claim, scope) => {
    const { value, basis } = truthFor(claim.kind, truth);
    const entry = { ...claim, computed: value, basis, scope };
    if (claim.stated === value) agreements.push(entry);
    else if (scope === "ledger") historical.push(entry);
    else conflicts.push(entry);
  };

  // (a) The table's Status column — this runner owns it and regenerates it.
  for (const row of parsed.rows) {
    for (const claim of scanClaims(row.status, rel(GATES_FILE))) {
      record({ ...claim, line: row.sourceLine, gate: row.id }, "table");
    }
  }

  // (b) Every other .agent-state/*.md line — reported, never rewritten.
  //     Two exclusions, both to keep the check from reading its own output:
  //     the table rows already handled above, and the generated note block,
  //     whose text quotes the very numbers it just corrected.
  const tableLineNumbers = new Set(parsed.rows.map((r) => r.sourceLine));
  for (const name of readdirSync(STATE_DIR).filter((f) => f.endsWith(".md")).sort()) {
    const file = path.join(STATE_DIR, name);
    const text = readFileSync(file, "utf8");
    const generated = new Set();
    if (file === GATES_FILE) {
      const lines = text.split(/\r?\n/);
      const from = lines.findIndex((l) => l.trim() === BEGIN_MARK);
      const to = lines.findIndex((l) => l.trim() === END_MARK);
      if (from >= 0 && to > from) for (let i = from; i <= to; i += 1) generated.add(i + 1);
    }
    for (const claim of scanClaims(text, rel(file))) {
      if (file === GATES_FILE && (tableLineNumbers.has(claim.line) || generated.has(claim.line))) continue;
      record(claim, name === "DECISIONS.md" ? "ledger" : "prose");
    }
  }

  return { conflicts, agreements, historical };
}

/* ------------------------------------------------------------------ *
 * 6. Execution
 * ------------------------------------------------------------------ */

/**
 * Fresh detail for the Status cell, taken from the child's own output. Bun
 * echoes the underlying command as `$ …` before running it; that echo is the
 * command, not a result, so it is dropped. Test-runner counters are preferred
 * over the last line because they are the number a reader actually wants.
 */
function tailOf(child) {
  const clean = (blob) => (blob ?? "").split(/\r?\n/).map((l) => l.trim()).filter((l) => l && !l.startsWith("$ "));
  const out = clean(child.stdout);
  const err = clean(child.stderr);
  const counters = [...out, ...err].filter((l) => /^(ℹ|#)\s*(tests|pass|fail|skipped|cancelled)\b/.test(l));
  if (counters.length > 0) return counters.join(", ").slice(0, 200);
  // A report printed as pretty JSON: keep its scalars, drop its paths. Absolute
  // local paths must not be baked into a tracked document.
  try {
    const parsed = JSON.parse(out.join("\n"));
    if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
      const scalars = Object.entries(parsed)
        .filter(([, v]) => typeof v === "number" || typeof v === "boolean")
        .map(([k, v]) => `${k}=${v}`);
      if (scalars.length > 0) return scalars.join(", ").slice(0, 200);
    }
  } catch {
    // not a JSON report; fall through to the last line
  }
  return (out[out.length - 1] ?? err[err.length - 1] ?? "").slice(0, 200);
}

function runGate(row, plan) {
  const details = [];
  let worstExit = 0;
  const started = Date.now();
  for (const step of plan.exec) {
    process.stdout.write(`  → ${step.display} … `);
    const t0 = Date.now();
    const child = spawnSync(step.binary, step.args, { cwd: ROOT, encoding: "utf8", shell: false });
    const ms = Date.now() - t0;
    if (child.error) {
      console.log(`spawn-error ${child.error.code ?? child.error.message} (${(ms / 1000).toFixed(1)}s)`);
      log({ gate: row.id, event: "step", command: step.display, mappedFrom: step.mappedFrom, exitCode: null, spawnError: child.error.code ?? child.error.message, durationMs: ms });
      worstExit = worstExit || 127;
      details.push(`${step.display}: spawn-error ${child.error.code ?? child.error.message}`);
      continue;
    }
    console.log(`exit ${child.status} (${(ms / 1000).toFixed(1)}s)`);
    log({ gate: row.id, event: "step", command: step.display, mappedFrom: step.mappedFrom, exitCode: child.status, durationMs: ms });
    if (child.status !== 0) {
      worstExit = worstExit || child.status;
      if (child.stderr) console.error(child.stderr.split(/\r?\n/).slice(-25).join("\n"));
    }
    const tail = tailOf(child);
    if (tail) details.push(tail);
  }
  return { exitCode: worstExit, durationMs: Date.now() - started, detail: details.join("; ") };
}

/* ------------------------------------------------------------------ *
 * 7. Main
 * ------------------------------------------------------------------ */

const truth = computeCatalogTruth();
console.log(`[release-gates] run ${RUN_ID}`);
console.log(`[release-gates] catalog truth (node scripts/agent/rights-audit.mjs): total=${truth.total} approved=${truth.approved} publishable=${truth.publishable}`);
log({ event: "truth", source: "scripts/agent/rights-audit.mjs", total: truth.total, approved: truth.approved, publishable: truth.publishable });

const bun = resolveBun();
if (!bun) abort("bun is unresolvable (not at C:\\Users\\serge\\.cherrystudio\\bin\\bun.exe and not on PATH) — AGENTS.md makes bun canonical and this runner will not fall back to npm.");

const originalText = readFileSync(GATES_FILE, "utf8");
const parsed = parseGatesDoc(originalText);

// ---- command plan, printed before anything executes -------------------
const plans = new Map();
for (const row of parsed.rows) {
  const tokens = extractTokens(row.command);
  const mapped = tokens.map((t) => mapCommand(t, bun));
  plans.set(row.id, { exec: mapped.filter((m) => m.kind === "exec"), refs: mapped.filter((m) => m.kind === "reference") });
}

console.log("\n[release-gates] COMMAND PLAN (documented → executed)");
for (const row of parsed.rows) {
  const plan = plans.get(row.id);
  const documented = extractTokens(row.command);
  console.log(`  ${row.id}: documented ${documented.length ? documented.map((d) => `\`${d}\``).join(", ") : "(none)"}`);
  for (const step of plan.exec) console.log(`      executes: ${step.binary === bun ? "bun" : "node"} ${step.args.join(" ")}${step.mappedFrom ? `   [mapped from \`${step.mappedFrom}\`]` : ""}`);
  for (const ref of plan.refs) console.log(`      not executable: ${ref.why}`);
}

for (const [id, plan] of plans) {
  for (const step of plan.exec) {
    const base = path.basename(step.binary).toLowerCase();
    if (FORBIDDEN_RUNNERS.test(base) || step.args.some((a) => FORBIDDEN_RUNNERS.test(a))) {
      abort(`gate ${id} would spawn a forbidden package manager (${base} ${step.args.join(" ")}); bun is canonical.`);
    }
  }
}
console.log(`[release-gates] forbidden-runner check: 0 npm/npx/pnpm/yarn spawns in the plan (binaries: ${[...new Set([...plans.values()].flatMap((p) => p.exec.map((s) => path.basename(s.binary))))].join(", ") || "none"})`);

// ---- numeric cross-check ---------------------------------------------
const { conflicts, agreements, historical } = crossCheck(truth, parsed);
console.log(
  `\n[release-gates] numeric cross-check over .agent-state/*.md: ${agreements.length} claim(s) agree with computed truth, ` +
    `${conflicts.length} conflict(s), ${historical.length} superseded ledger claim(s) (DECISIONS.md — history, not status)`,
);
for (const h of historical) {
  console.log(`  HISTORICAL-CLAIM [ledger] ${h.file}:${h.line} states ${h.stated} ${h.kind} (computed today: ${h.computed}). Append-only ledger — recorded as history, not rewritten.`);
  log({ event: "historical-claim", finding: "HISTORICAL-CLAIM", file: h.file, line: h.line, kind: h.kind, stated: h.stated, computed: h.computed });
}
for (const c of conflicts) {
  console.log(
    `  SOURCE-OF-TRUTH-CONFLICT [${c.scope}] ${c.file}:${c.line}${c.gate ? ` (${c.gate})` : ""} states ${c.stated} ${c.kind}; ` +
      `catalog/approved-artworks.json via scripts/agent/rights-audit.mjs computes ${c.computed} (${c.basis}). ` +
      `Resolution: computed value wins${c.scope === "table" ? " — rewritten below." : " — REPORTED ONLY; this runner rewrites no prose or ledger line."}`,
  );
  log({ event: "conflict", finding: "SOURCE-OF-TRUTH-CONFLICT", scope: c.scope, file: c.file, line: c.line, gate: c.gate ?? null, kind: c.kind, stated: c.stated, computed: c.computed, basis: c.basis, resolution: c.scope === "table" ? "rewritten" : "reported" });
}

if (DRY_RUN) {
  console.log("\n[release-gates] --dry-run: nothing executed, nothing written.");
  process.exit(0);
}

// ---- execute ----------------------------------------------------------
console.log("\n[release-gates] EXECUTING");
const results = new Map();
for (const row of parsed.rows) {
  const plan = plans.get(row.id);
  const blocked = PRECONDITIONS[row.id]?.();
  if (blocked) {
    console.log(`  ${row.id}: NOT RUN — ${blocked}`);
    results.set(row.id, log({ gate: row.id, event: "gate", status: "not-run", reason: blocked, exitCode: null }));
    continue;
  }
  if (plan.exec.length === 0) {
    const why = plan.refs.length > 0
      ? `no executable command in the Command / Check column — it names only ${plan.refs.map((r) => `\`${r.text}\``).join(", ")} plus prose, so nothing could be executed and no status can be certified`
      : "no executable command in the Command / Check column — it is prose only, so nothing could be executed and no status can be certified";
    console.log(`  ${row.id}: NOT RUN — ${why}`);
    results.set(row.id, log({ gate: row.id, event: "gate", status: "not-run", reason: why, exitCode: null }));
    continue;
  }
  console.log(`  ${row.id}:`);
  const outcome = runGate(row, plan);
  results.set(row.id, log({
    gate: row.id,
    event: "gate",
    status: outcome.exitCode === 0 ? "pass" : "fail",
    exitCode: outcome.exitCode,
    durationMs: outcome.durationMs,
    commands: plan.exec.map((s) => s.display),
    mappedFrom: plan.exec.map((s) => s.mappedFrom).filter(Boolean),
    detail: outcome.detail,
  }));
}

/**
 * PASS is derivable ONLY from a logged, numeric, zero exit code. There is no
 * other branch that can produce the string "PASS".
 */
function certifyStatus(row) {
  const rec = results.get(row.id);
  if (!rec) return { text: "**NOT RUN** — the runner produced no record for this gate", pass: false };
  if (rec.status === "not-run") return { text: `**NOT RUN** — ${cellSafe(rec.reason)}`, pass: false };
  if (rec.logged !== true) {
    return { text: `**NOT RUN** — the gate executed (exit ${rec.exitCode}) but its result could not be written to the run log (${cellSafe(rec.logError ?? "unknown")}); an uncaptured result is not a certification`, pass: false };
  }
  if (typeof rec.exitCode !== "number") return { text: "**NOT RUN** — no exit code was captured", pass: false };
  const secs = `${(rec.durationMs / 1000).toFixed(1)}s`;
  const counts = ["G4", "G6"].includes(row.id)
    ? ` — computed catalog truth: ${truth.approved} approved → ${truth.publishable} publishable (${truth.total - truth.publishable} delete-tier excluded), per \`node scripts/agent/rights-audit.mjs\``
    : "";
  const detail = rec.detail ? ` — ${cellSafe(rec.detail)}` : "";
  if (rec.exitCode === 0) return { text: `**PASS** (exit 0, ${secs}, ${RUN_ID})${detail}${counts}`, pass: true };
  return { text: `**FAIL** (exit ${rec.exitCode}, ${secs}, ${RUN_ID})${detail}${counts}`, pass: false };
}

// ---- rewrite the document --------------------------------------------
const newHeader = `| Gate | Requirement | Command / Check (bun — mapped from the documented command) | Status (${TODAY}) |`;
const newRows = parsed.rows.map((row) => {
  const plan = plans.get(row.id);
  const commandCell = [
    ...plan.exec.map((s) => `\`${s.display}\``),
    ...plan.refs.map((r) => `\`${r.text}\``),
  ].join(", ") || cellSafe(strip(row.command));
  return `| ${row.gate} | ${row.requirement} | ${commandCell} | ${certifyStatus(row).text} |`;
});

const mappings = [...new Set([...plans.values()].flatMap((p) => p.exec.map((s) => s.mapping).filter(Boolean)))];
const notRun = parsed.rows.filter((r) => results.get(r.id)?.status === "not-run");

const noteBlock = [
  BEGIN_MARK,
  "",
  `**How this table was produced.** \`node scripts/agent/release-gates.mjs\` executed it on ${TODAY} (run \`${RUN_ID}\`). Every Status cell above is derived from a child-process exit code captured during that run and written to \`~/.claude/logs/release-gates.jsonl\`; no cell can read **PASS** without one.`,
  "",
  `**Command mapping (npm is never spawned — \`bun\` is canonical per AGENTS.md).** The documented Command column was rewritten to the form actually executed:`,
  "",
  ...(mappings.length > 0 ? mappings.map((m) => `- \`${m}\``) : ["- (no mapping needed — every documented command was already canonical)"]),
  "",
  `**NOT RUN (${notRun.length}).** A gate that needs credentials, a live service, a browser, or an absent CLI is recorded NOT RUN with its reason. It never becomes PASS by default:`,
  "",
  ...(notRun.length > 0
    ? notRun.map((r) => `- **${r.id}** — ${cellSafe(results.get(r.id).reason)}`)
    : ["- (none)"]),
  "",
  `**Numeric cross-check against computed catalog truth.** \`node scripts/agent/rights-audit.mjs\` reports **${truth.total} total / ${truth.approved} approved / ${truth.publishable} publishable** (${truth.total - truth.publishable} delete-tier excluded). Every \`<N> published|approved|projected\` claim in \`.agent-state/*.md\` was compared against it: **${agreements.length} agree, ${conflicts.length} conflict, ${historical.length} superseded ledger claim(s)** in \`DECISIONS.md\` (an append-only record of dated decisions — its numbers are history by construction and are never rewritten).`,
  ...(conflicts.length > 0
    ? [
        "",
        ...conflicts.map(
          (c) =>
            `- \`SOURCE-OF-TRUTH-CONFLICT\` — \`${c.file}\`:${c.line}${c.gate ? ` (${c.gate})` : ""} stated **${c.stated} ${c.kind}**; \`catalog/approved-artworks.json\` computes **${c.computed}** (${c.basis}). Computed value wins${c.scope === "table" ? "; the Status column above carries the corrected number." : "; reported only — this runner rewrites no prose or append-only ledger line."}`,
        ),
      ]
    : []),
  "",
  END_MARK,
].join("\n");

const before = parsed.lines.slice(0, parsed.headerIndex);
let after = parsed.lines.slice(parsed.tableEnd);
const oldBegin = after.findIndex((l) => l.trim() === BEGIN_MARK);
if (oldBegin >= 0) {
  const oldEnd = after.findIndex((l) => l.trim() === END_MARK);
  if (oldEnd < 0) abort(`${GATES_FILE} has an unterminated ${BEGIN_MARK} block.`);
  after = [...after.slice(0, oldBegin), ...after.slice(oldEnd + 1)];
}
while (after.length > 0 && after[0].trim() === "") after.shift();

const rewritten = [
  ...before,
  newHeader,
  parsed.lines[parsed.headerIndex + 1],
  ...newRows,
  "",
  noteBlock,
  "",
  ...after,
].join("\n");

writeFileSync(GATES_FILE, rewritten.endsWith("\n") ? rewritten : `${rewritten}\n`);
console.log(`\n[release-gates] rewrote ${rel(GATES_FILE)} (Status dated ${TODAY})`);

// ---- append an ADR when a conflict was corrected ----------------------
const corrected = conflicts.filter((c) => c.scope === "table");
if (corrected.length > 0) {
  const decisions = readFileSync(DECISIONS_FILE, "utf8");
  const nextAdr = String(
    Math.max(0, ...[...decisions.matchAll(/^##\s+ADR-(\d+)/gm)].map((m) => Number(m[1]))) + 1,
  ).padStart(3, "0");
  const reported = conflicts.filter((c) => c.scope !== "table");
  const adr = [
    "",
    `## ADR-${nextAdr} (${TODAY}): Release-Gate Status Table Corrected Against Computed Catalog Truth`,
    "",
    `- **Context**: \`.agent-state/RELEASE_GATES.md\` and \`catalog/approved-artworks.json\` are both designated sources of truth, and they disagreed. The hand-maintained Status column asserted ${corrected.map((c) => `**${c.stated} ${c.kind}** (${c.gate})`).join(", ")}, while the catalog computes **${truth.total} total / ${truth.approved} approved / ${truth.publishable} publishable** (${truth.total - truth.publishable} delete-tier excluded). A freshness-by-date check cannot detect this class of drift; a numeric cross-check can.`,
    `- **Decision**: The computed value wins. \`scripts/agent/release-gates.mjs\` rewrote the Status column from this run's captured exit codes and the computed counts. Corrections (old → new): ${corrected.map((c) => `${c.gate ?? c.file}: ${c.stated} ${c.kind} → ${c.computed} ${c.kind}`).join("; ")}.`,
    `- **Evidence command**: \`node scripts/agent/rights-audit.mjs\` (P10's auditor; this runner parses its JSON and does not recompute the counts) → \`{"total":${truth.total},"approved":${truth.approved},"publishable":${truth.publishable}}\`, captured ${TODAY} in run \`${RUN_ID}\` and logged to \`~/.claude/logs/release-gates.jsonl\`.`,
    `- **Scope**: only the RELEASE_GATES Status column is machine-rewritten. ${reported.length > 0 ? `${reported.length} further numeric claim(s) outside it were reported, not rewritten (${reported.map((c) => `\`${c.file}\`:${c.line} states ${c.stated} ${c.kind}, computed ${c.computed}`).join("; ")}) — the runner cannot verify the surrounding sentence's arithmetic, so a human decides whether those are stale status or correct history.` : "No present-tense numeric claim outside it conflicted with computed truth this run."} \`DECISIONS.md\` is append-only: ${historical.length} superseded number(s) in earlier ADRs are correct *as history*, are reported as \`HISTORICAL-CLAIM\` rather than as conflicts, and are never edited.`,
    `- **Impact**: The release-gate table is now machine-generated per run. Any gate needing credentials, a live service, a browser, or an absent CLI reads **NOT RUN** with its reason, and **PASS** is derivable only from a logged exit code. Re-running the runner after this correction finds no table conflict and appends no further ADR.`,
    "",
  ].join("\n");
  appendFileSync(DECISIONS_FILE, decisions.endsWith("\n") ? adr : `\n${adr}`);
  console.log(`[release-gates] appended ADR-${nextAdr} to ${rel(DECISIONS_FILE)} (append-only; no existing entry edited)`);
  log({ event: "adr", id: `ADR-${nextAdr}`, file: rel(DECISIONS_FILE), corrections: corrected.map((c) => ({ gate: c.gate, kind: c.kind, old: c.stated, new: c.computed })) });
}

// ---- summary ----------------------------------------------------------
const tally = { pass: 0, fail: 0, "not-run": 0 };
for (const row of parsed.rows) tally[results.get(row.id).status] += 1;
console.log(`\n[release-gates] ${tally.pass} PASS · ${tally.fail} FAIL · ${tally["not-run"]} NOT RUN · ${conflicts.length} conflict(s)`);
console.log(`[release-gates] run log: ${LOG}`);
log({ event: "summary", ...tally, conflicts: conflicts.length, npmSpawns: 0 });
process.exit(tally.fail > 0 ? 1 : 0);
