import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
const outfitFont = localFont({ src: [{ path: "../../public/assets/NeueHaasGroteskTextPro-Regular.woff2", weight: "400", style: "normal" }, { path: "../../public/assets/NeueHaasGroteskTextPro-Medium.woff2", weight: "700", style: "normal" }, { path: "../../public/assets/NeueHaasGroteskTextPro-Bold.woff2", weight: "800", style: "normal" }], variable: "--font-outfit", display: "swap", fallback: ["ui-sans-serif", "system-ui", "Arial", "sans-serif"] });
export const metadata: Metadata = { title: "OUTFIT® by ++hellohello", description: "Created by the ++hellohello team, this store and signature collection celebrates our collective creativity and passion for apparel. Carefully designed.", icons: { icon: "/favicon.ico" }, openGraph: { title: "OUTFIT® by ++hellohello", description: "Signature collection by ++hellohello. Carefully designed apparel for the creatively passionate.", type: "website", url: "https://outfit.hellohello.is", siteName: "OUTFIT®" }, twitter: { card: "summary_large_image", title: "OUTFIT® by ++hellohello", description: "Signature collection by ++hellohello. Carefully designed apparel." } };
const JSONLD = { "@context": "https://schema.org", "@type": "Store", name: "OUTFIT®", description: "Signature collection by ++hellohello. Carefully designed apparel.", brand: { "@type": "Brand", name: "OUTFIT®" }, founder: { "@type": "Organization", name: "++hellohello", url: "https://www.hellohello.is" }, address: { "@type": "PostalAddress", streetAddress: "Libertad 2529, Office 102", addressLocality: "Montevideo", addressCountry: "UY" } };
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (<html lang="en" suppressHydrationWarning className={`${outfitFont.className}`}><head><meta name="color-scheme" content="light dark" /><link rel="preload" as="image" href="/assets/preloader-1.jpg" fetchPriority="high" /><link rel="preload" as="image" href="/assets/preloader-2.jpg" fetchPriority="high" /><link rel="preload" as="image" href="/assets/preloader-3.jpg" fetchPriority="high" /><link rel="preload" as="font" type="font/woff2" href="/assets/NeueHaasGroteskTextPro-Regular.woff2" crossOrigin="anonymous" /><link rel="preload" as="font" type="font/woff2" href="/assets/NeueHaasGroteskTextPro-Medium.woff2" crossOrigin="anonymous" /><script dangerouslySetInnerHTML={{ __html: `(function(){try{var t=localStorage.getItem('theme');if(!t){t='red';}document.documentElement.setAttribute('data-theme',t);}catch(e){document.documentElement.setAttribute('data-theme','red');}})();` }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(JSONLD) }} /></head><body className={`${outfitFont.className} bg-cream selection:bg-red red:bg-cream red:text-red red:selection:bg-black text-black selection:text-white dark:bg-black dark:text-white`}>{children}<Toaster /></body></html>);
}
