// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/artcovr-discovery-controls-exploration/FacetRail.tsx": () => import("../components/mockups/artcovr-discovery-controls-exploration/FacetRail.tsx"),
  "./components/mockups/artcovr-discovery-controls-exploration/FilterDrawer.tsx": () => import("../components/mockups/artcovr-discovery-controls-exploration/FilterDrawer.tsx"),
  "./components/mockups/artcovr-discovery-controls-exploration/PaletteFirst.tsx": () => import("../components/mockups/artcovr-discovery-controls-exploration/PaletteFirst.tsx"),
  "./components/mockups/artcovr-discovery-controls-redesign/Current.tsx": () => import("../components/mockups/artcovr-discovery-controls-redesign/Current.tsx"),
  "./components/mockups/artcovr-discovery-controls-redesign/Editorial.tsx": () => import("../components/mockups/artcovr-discovery-controls-redesign/Editorial.tsx"),
  "./components/mockups/artcovr-facet-orbit/FacetOrbit.tsx": () => import("../components/mockups/artcovr-facet-orbit/FacetOrbit.tsx"),
  "./components/mockups/artcovr-hero-wordmark-audit/Current.tsx": () => import("../components/mockups/artcovr-hero-wordmark-audit/Current.tsx")
};
