// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/artcovr-hero-wordmark-audit/Current.tsx": () => import("../components/mockups/artcovr-hero-wordmark-audit/Current.tsx"),
  "./components/mockups/artcovr-facet-orbit/FacetOrbit.tsx": () => import("../components/mockups/artcovr-facet-orbit/FacetOrbit.tsx")
};
